### ISSUE TITLE
Loading the SlideOverController fails

### ISSUE THREAD

**Issue by GantMan** [infinitered/redpotion#32] opened 2015-01-02 03:32 UTC
When trying to implement SlideOverController RMQ plugin the load order issue rears its ugly head :goberserk: 

https://github.com/infinitered/rmq-slide-over-control

**Comment by squidpunch** [comment] 2015-01-02 23:11
hrmm, interesting - I will see if i can reproduce in a sample app.

**Comment by squidpunch** [comment] 2015-01-03 00:24
at first look I think this is a problem with RMQ or the slideover gem because I just did a new RMQ app and included that slideover gem and I dont see the slideover files compiled and it crashing updating a new RMQ app to use the slideover control like suggested in the gem.

The fact that a file isnt even in the compile list is a bit interesting to me.

I can push my sample app later showing that its not working just using RMQ directly - but I think this issue is outside of RedPotion.

**Comment by GantMan** [comment] 2015-01-03 23:00
I @twerth  is using this gem in an RMQ project...   So it seemed to be a RedPotion issue, but might be something to do with a latest RM version?

**Comment by squidpunch** [comment] 2015-01-04 04:20
Yeah I knew that @twerth had used the gem in a project, or I thought he was.  It's just weird, I created a new project, using RMQ 1.0, added this gem, copied the implementation from the readme, and I dont even see the gem files attempt to compile, clearly I did something wrong.  I will give it a look again soon if I can sneak in the time to do so.

**Comment by squidpunch** [comment] 2015-01-04 04:30
Sure you already gave this a try, but maybe it requires a `rake clean:all`.  I just pulled down the slideover gem repo, and tweaked the gemfile to use redpotion (removed the gemspec call in the gemfile, updated it to refer to redpotion and the github path to the plugin gem) and it works for me.  Maybe we could try and pair on your project to try and sort it out if you want @GantMan because I cant seem to recreate the problem to try and help solve it. :(

**Comment by GantMan** [comment] 2015-01-04 04:35
much appreciated for your time!

**Comment by andrewhavens** [comment] 2016-05-09 23:09
@squidpunch @GantMan Did you two ever resolve this issue? Was it an issue with the plugin? Can we close this issue for RedPotion?

**Closed** 2016-05-10 01:51 UTC
Labels: bug
